# fly.toml app configuration file generated for travel-gpt-backend on 2023-05-27T15:30:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "travel-gpt-backend"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[env]
  AWS_DEFAULT_REGION = "ap-southeast-1"
  AWS_S3_BUCKET_NAME = "chinholin.com"
  AWS_S3_FILE_PATH = "travel-gpt/dalle"
  FLASK_HOST = "0.0.0.0"
  FLASK_PORT = "5000"
  MOOD_IMAGE_SIZE = "512x512"
  MOOD_MESSAGE_MODEL = "gpt-3.5-turbo"

[[services]]
  protocol = "tcp"
  internal_port = 5000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
