# fly.toml file generated for travel-gpt-backend on 2023-05-12T23:37:51+08:00

app = "travel-gpt-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  FLASK_HOST = "0.0.0.0"
  FLASK_PORT = "5000"
  AWS_DEFAULT_REGION = "ap-southeast-1"
  AWS_S3_BUCKET_NAME = "chinholin.com"
  AWS_S3_FILE_PATH = "travel-gpt/dalle"
  MOOD_MESSAGE_MODEL = "text-davinci-003"
  MOOD_IMAGE_SIZE = "512x512"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
